 name: Wake up Streamlit App

on:
  schedule:
    # 20分おきに実行 (分 時 日 月 曜日) UTC時間
    - cron: "*/20 * * * *"
  workflow_dispatch: # 手動実行ボタンも有効化

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: Poke App
        run: |
          # ここにアプリのURLを入れてください
          curl https://onishi.streamlit.app
